### ISSUE TITLE
DISEÑO DE OBJETOS EN BLENDER

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-team-pc-box#2]
[DISEÑO DE OBJETOS EN BLENDER.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-team-pc-box/files/8241295/DISENO.DE.OBJETOS.EN.BLENDER.pdf)

**Comment by Jaimer117** [comment]
Trabajo bien hecho calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
